# Kubernetes Service Account with Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APP_NAME}-sa
  labels:
    app: ${APP_NAME}
  annotations:
    azure.workload.identity/client-id: ${IDENTITY_CLIENT_ID}
