# ASO v2: Federated Identity Credential for Workload Identity
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: {{ include "container-cosmosdb-monitoring.identityName" . }}-federated
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-cosmosdb-monitoring.labels" . | nindent 4 }}
spec:
  azureName: {{ .Values.appName }}-k8s-federated
  owner:
    name: {{ include "container-cosmosdb-monitoring.identityName" . }}
  # OIDC issuer URL from AKS cluster
  issuer: {{ include "container-cosmosdb-monitoring.oidcIssuerUrl" . }}
  # Subject must match exactly: system:serviceaccount:<namespace>:<service-account-name>
  subject: {{ include "container-cosmosdb-monitoring.workloadIdentitySubject" . }}
  # Standard audience for Azure workload identity
  audiences:
    - api://AzureADTokenExchange
