# Kubernetes Service Account with Workload Identity annotation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container-cosmosdb-monitoring.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-cosmosdb-monitoring.labels" . | nindent 4 }}
  annotations:
    # Workload Identity: Link to Azure Managed Identity
    # The client ID is retrieved from the ASO-managed identity's status
    azure.workload.identity/client-id: {{ printf "${%s:clientId}" (include "container-cosmosdb-monitoring.identityName" .) }}
