{{- $platformCM := lookup "v1" "ConfigMap" (default "kube-public" .Values.infrastructure.platformConfigMapNamespace) (default "aso-platform-config" .Values.infrastructure.platformConfigMap) }}
{{- $oidcIssuerUrl := .Values.oidcIssuerUrl | default (get ($platformCM.data | default dict) "oidcIssuerUrl") }}
{{- if $oidcIssuerUrl }}
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: {{ include "container-storage-mi.managedIdentityName" . }}-fed-cred
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-storage-mi.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  owner:
    name: {{ include "container-storage-mi.managedIdentityName" . }}
  audiences:
    - api://AzureADTokenExchange
  issuer: {{ $oidcIssuerUrl }}
  subject: system:serviceaccount:{{ include "container-storage-mi.serviceAccountNamespace" . }}:{{ include "container-storage-mi.serviceAccountName" . }}
{{- end }}
