apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: {{ include "container-storage-mi.managedIdentityName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-storage-mi.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  location: {{ .Values.location | default "swedencentral" }}
  owner:
    {{- if .Values.resourceGroupArmId }}
    armId: {{ .Values.resourceGroupArmId }}
    {{- else }}
    name: {{ .Values.resourceGroup }}
    {{- end }}
  operatorSpec:
    configMaps:
      principalId:
        name: {{ .Values.appName }}-identity-config
        key: principalId
      clientId:
        name: {{ .Values.appName }}-identity-config
        key: clientId
      tenantId:
        name: {{ .Values.appName }}-identity-config
        key: tenantId
