# Kubernetes Service Account for Workload Identity
# Pods using this service account can authenticate to Azure as the managed identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container-storage-mi.serviceAccountName" . }}
  namespace: {{ include "container-storage-mi.serviceAccountNamespace" . }}
  labels:
    {{- include "container-storage-mi.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
    azure.workload.identity/use: "true"
    app.kubernetes.io/port: "{{ .Values.port }}"
  annotations:
    # Client ID will be populated from the ConfigMap after identity is created
    # For now, we use a placeholder that should be updated or use external-secrets
    azure.workload.identity/client-id: "pending-identity-creation"
---
# ConfigMap with connection info for the application
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-storage-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "container-storage-mi.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  APP_NAME: {{ .Values.appName | quote }}
  BLOB_CONTAINER_NAME: {{ .Values.blobContainerName | quote }}
  PORT: {{ .Values.port | quote }}
  # Storage account name for SDK configuration
  STORAGE_ACCOUNT_NAME: {{ include "container-storage-mi.storageAccountName" . | quote }}
  # Service account name for workload identity
  SERVICE_ACCOUNT_NAME: {{ include "container-storage-mi.serviceAccountName" . | quote }}
